import "./globals.css";
import { Inter } from "next/font/google";
import Bottombar from "./components/bottombar";
import { MyContextProvider } from "./MyContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div>
        <Link href = "/">Home page</Link>
        <Link href = "/about">About page</Link>
        </div> */}
        <MyContextProvider>
          {children}
        </MyContextProvider>
        
        <Bottombar/>
      </body>
    </html>
  );
}
